### ISSUE TITLE
Use UTF-8 as default encoding instead of ASCII

### ISSUE THREAD

**Issue by gvenzl** [oracle/python-cx_Oracle#409]
All other major databases use `UTF-8` as the default characterset encoding for connections while cx_Oracle is using `ASCII`. Given how limited and rarely useful `ASCII` is these days, it makes more sense to follow "common convention" and Oracle's default since 11g: `UTF-8`

MySQL: https://dev.mysql.com/doc/connector-python/en/connector-python-connectargs.html
Postgres: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS (seems to determine the default from the server)
SQL Server: https://pymssql.readthedocs.io/en/latest/ref/pymssql.html#connection-class

**Comment by gitpickle** [comment]
+1

**Comment by anthony-tuininga** [comment]
The default is currently based on the Oracle Client library's default -- which is indeed ASCII if the environment variable NLS_LANG is not set. If I change the default to be UTF-8 that implies that the environment variable NLS_LANG will be ignored. I personally don't have a problem with that, though, as the encoding is now only relevant for performance (since if the database encoding itself is not UTF-8 there will be conversion required between the two encodings). As far as the Python user is concerned, the encoding isn't relevant as they simply get back strings (which don't have an encoding). I'll see if @cjbj has an objection to making this change.

**Comment by gvenzl** [comment]
I think the `NLS_LANG` environment variable should still be honored to continue to provide the same behavior that users are used to for many years. So ideally the order would be:

1) use what's provided via the `encoding`, `nencoding` parameter
2) use the value provided by `NLS_LANG`
3) default to `UTF-8`

I believe that would mean that rather than just setting encoding from `None` to `UTF-8` some more changes are required in the underlying code.

An interesting remark about relevance for performance only. When loading a `UTF-8` file with no `enconding` set and a database running in `AL32UTF8`, the Python driver will throw a:
```
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
```
This is with cx-Oracle 7.2.2.

**Comment by cjbj** [comment]
That order seems straightforward but Anthony has some issues, particularly on Windows.  We'll review and make a decision for cx_Oracle 8.

What do you mean "loading a ... file"?

**Comment by cjbj** [comment]
For the record, NLS_NCHAR is the variable that determines the client's national character set (e.g. for NCHAR, NVARCHAR, and NCLOB columns).  This needs to be considered in the plans.

**Comment by anthony-tuininga** [comment]
Agreed. I would set its default to "UTF-8" as well -- unless of course there is a good reason to use "UTF-16" in light of the fact that NCHAR, NVARCHAR2 and NCLOB data is stored in UCS-2 code points regardless of the database character set.

I also wonder what you mean about loading a file. We are talking about the way that cx_Oracle sends data to the database and how it fetches data from the database. It has nothing to do with loading a file!

**Comment by gvenzl** [comment]
Sorry, I shouldn't have said file value. I also forgot to add that the error is thrown only when a non-ascii character is present in the value, of course.

**Comment by anthony-tuininga** [comment]
Well, when you pass data to the database, it is encoded into the encoding specified when you created the connection (or via NLS_LANG and if that isn't set ASCII). By changing the default to UTF-8 this problem would be avoided.

**Comment by gvenzl** [comment]
Yes, indeed, I was referring to your sentence above:
>  I personally don't have a problem with that, though, as the encoding is now only relevant for performance (since if the database encoding itself is not UTF-8 there will be conversion required between the two encodings)

Perhaps I misunderstood what you meant with the sentence but there is not only a performance relevance with `encoding` but also a functional one.

**Comment by anthony-tuininga** [comment]
It is definitely **not** a functional issue. The encoding can be set to anything that supports the data and the application code will continue to work -- no matter what that encoding is. In order to cover all possible data, one of the universal encodings is recommended -- either UTF-8, UTF-16, etc. but the most commonly used one is indeed UTF-8. Setting the default to UTF-8 should not have any impact on the functaility of the applications using cx_Oracle. If you think that there is such a case, please say on!

**Comment by gvenzl** [comment]
Thanks for clarifying, @anthony-tuininga, I get it now!
Agreed, changing the default to `UTF-8` should not have any functional impact.

**Comment by anthony-tuininga** [comment]
Looking at the Python/C API there are a number of optimizations that are in place when exclusively using UTF-8. As such, I think it might be better to not just make the default UTF-8 but to make it exclusively UTF-8. This is already done by most of the other drivers that are available and it makes usage much simpler. If this were to be done, as noted earlier there should be no functional impact. If a different encoding was specified an exception could be raised or a warning could be generated indicating that the value is simply ignored (and in version 9 the argument would be entirely removed, thereby causing an exception). Any thoughts on that?

**Comment by anthony-tuininga** [comment]
@zzzeek, your ccomments would be welcome, especially in light of the documentation in SQLAlchemy found in issue #439.

**Comment by zzzeek** [comment]
other client libraries don't honor NLS_LANG these days?   I've been using NLS_LANG since the prior millennia, literally, with Perl, whatever.     when you say "other drivers" you mean Oracle drivers?    I suppose if you are in fact targeting only Python 3, then you're good now, because we don't send bytestrings anymore and there's no opportunity for other encodings to be programmatically present.    I guess it could work for Py3k.

**Comment by anthony-tuininga** [comment]
Since I am referring to other Oracle drivers. Anything created recently simply uses UTF-8. Perl (and currently cx_Oracle) are old enough to make use of NLS_LANG and "grew up" with ASCII. And yes, cx_Oracle 8 will only target Python 3. There is another request (#385) that would permit passing data in other encodings if desired, but SQL statements and other string arguments would simply be passed as UTF-8 to the Oracle database.

**Comment by zzzeek** [comment]
they still need to do NLS_LANG within the scope of locale/territory and all that.   so it should probably send a warning if the NLS_LANG encoding portion is not compatible with UTF-8.   also not sure what the story is with things ike "AL32UTF8" and such, per https://community.oracle.com/thread/3514820?start=0&tstart=0 there may be some small differences but I have a feeling these don't matter for Python's utf-8 implementation anyway.

**Comment by Lexcon** [comment]
Referring to the remark

"There is another request (#385) that would permit passing data in other encodings if desired, but SQL statements and other string arguments would simply be passed as UTF-8 to the Oracle database"

If there would be 'raw' I would recommand having that two way (in/out). Suppose I have a lot of databases archived, some quite old and I might need to access them or even change a thing or two, and the encoding in the db is a mess. It would be handy to also be able to pass stuff in 'raw' like in py27.

I agree that onward utf-8 only is the way to go but I'd think it a regression if I'd have to revert to py27 to be able to mount an old database and poke in it. Also, I think the 'raw' functionality would not be in the way of the 'regular' and 'recommended' usage of the library. And I kind of assume that the current library has everything on board already to wire it up like this without incredible effort, but I could be wrong of course.

**Comment by zzzeek** [comment]
IIUC this doesnt affect the encoding of data as stored in the database itself, I think the idea is that any in-database encoding can be delivered over the wire as UTF-8.  if there's broken encodings in the DB, there's a parameter encodingErrors that in theory deals with this:  https://cx-oracle.readthedocs.io/en/latest/api_manual/cursor.html?highlight=encodingErrors#Cursor.var   certainly cx_Oracle needs to be able to read databases that store data in other encodings, I doubt that would change w/ what Anthony is proposing.

**Comment by anthony-tuininga** [comment]
Yes, this would not affect the encoding of data stored in the database itself and any in-database encoding is capable of being encoded in UTF-8, since UTF-8 is a universal character set. What @Lexcon is probably referring to, though, is the fact that people have stored data in the database in encoding A while the database stores data in encoding B. This can be done by manipulating NLS_LANG to mtach what the database is using (encoding B) but then proceed to use an entirely different encoding (encoding A) anyway! This makes the database incapable of transforming the data in the database to UTF-8 or may result in corrupted characters. This is the purpose behind the `encodingErrors` parameter. Being able to specify a different encoding for particular sets of data would allow you to work around this data corruption without losing data. Yes, the data should be fixed, but that is usually a difficult proposition! So I'll see about adding the ability to specify an alternative encoding or  the ability to take the bytes from the database in the database encoding but simply return the bytes directly instead of decoding them into a string -- and let the application figure it out on its own.

**Comment by anthony-tuininga** [comment]
I've pushed the changes to make UTF-8 the default encoding for all character data. I'll still consider a way to specify an alternative encoding for fetching specific columns.

**Comment by anthony-tuininga** [comment]
cx_Oracle 8 was just released with these changes.

**Comment by Lexcon** [comment]
Fantastic!On 26 Jun 2020 19:26, Anthony Tuininga <notifications@github.com> wrote:
cx_Oracle 8 was just released with these changes.

**Comment by Lexcon** [comment]
Anthony,

I've just reviewed it, looks good. Much appreciated.

We still have this thing though: we do a lot of database 
troubleshooting, fixing , patching rows. Databases that are used by 
other software, we just use Python to dig, tweak, investigate content. 
The occasional 10 year old backup. But our work should often affect 
existing rows and, should we write, write an entry back in the same 
encoding as is originally in the row, even when the encoding doesn't 
match the formal one in the db. Typically we use py27 + cd_Oracle and we 
can do that dirty type of work. Then the client says sorry for having 
such a messy database and we say it's cool we can handle it.

I think the current cx_Oracle is 'cleaner' and has a valid philosophy: 
just do things right and you won't run into problems encoding wise. 
However for that more low level 'dirty' interaction with the db we need 
to stick to py27 and cx_Oracle for now.

Robert

**Comment by anthony-tuininga** [comment]
I understand and appreciate the feedback. #385 addresses the need for such "dirty" work and I hope to include that change in the next release of cx_Oracle.
